dist: bionic
language: python
python:
  - "3.7"

# Taken from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION Cython
  - conda activate test-environment
  - conda install --yes --file test-requirements.txt
  - python setup.py install
script:
  - black --check timekeep
  - isort -rc timekeep -c -vb
  - python -m pytest tests/ --cov=timekeep  --cov-append
after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change
