dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r travis/travis-requirements.txt
  - python setup.py install
script:
  - black --check timekeep
  - isort -rc timekeep -c -vb
  - python -m pytest tests/ --cov=timekeep  --cov-append
after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change
