name: timekeep-dev
channels:
  - conda-forge
dependencies:
  - python=3.7.*
# mathematics
  - numpy >=1.16  # for numeric arrays
# timeseries utilities
  - tslearn
# unit testing
  - pytest >=4.4  # for unit testing
  - pytest-cov  # for code coverage
  - pytest-mock  # for mocker fixture
  - pytest-xdist  # for parallel tests
# code quality
  - flake8  # for static analysis
  - pylint  # for linting  # TODO: Check overlap with flake8
  - black  # for automatic code formatting
  - isort  # for import standardization
  - pip:
    - -e .  # project code